"""Add terminal and unit columns to JobLogForm

Revision ID: da8444e7a941
Revises: 
Create Date: 2024-01-28 02:54:20.067191

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'da8444e7a941'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('units')
    op.drop_table('terminals')
    with op.batch_alter_table('job_log_form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terminal', sa.String(length=15), nullable=False))
        batch_op.add_column(sa.Column('unit', sa.String(length=15), nullable=False))
        batch_op.drop_constraint('job_log_form_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('job_log_form_ibfk_2', type_='foreignkey')
        batch_op.drop_column('terminal_id')
        batch_op.drop_column('unit_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_log_form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('terminal_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('job_log_form_ibfk_2', 'units', ['unit_id'], ['id'])
        batch_op.create_foreign_key('job_log_form_ibfk_1', 'terminals', ['terminal_id'], ['id'])
        batch_op.drop_column('unit')
        batch_op.drop_column('terminal')

    op.create_table('terminals',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('terminal', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('units',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('unit', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
